### PR TITLE
LiveKit type aliases

### PR DESCRIPTION
**Pull request by boks1971**
Idea is to start with aliases so that this can be done in small steps.
The plan is to move to a type definition once we have most of the stuff
moved over to get stronger type checks.

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]
lgtm! perhaps `TrackID` etc as the type name? matching the var?

**Comment by boks1971** [comment]
> lgtm! perhaps `TrackID` etc as the type name? matching the var?

Cool @davidzhao. I can make the change. So, is the poll winner `trackID TrackID`?

**Comment by davidzhao** [comment]
> Cool @davidzhao. I can make the change. So, is the poll winner `trackID TrackID`?

Looks that way :)

**Comment by boks1971** [comment]
Changed it in this commit - https://github.com/livekit/protocol/pull/62/commits/2eae90f0d6d54d67a0658b37e55a772f39619029

**Pull request merged**
