### PR TITLE
Add topic to UserPacket

### PR DESCRIPTION
**Pull request by lukasIO**
Introduces a `topic` on `UserPacket` in order to make dataChannel usage more convenient on client and server SDKs

### CODE REVIEW

**Review by boks1971 — APPROVED** [review]

**Comment by lukasIO** [comment]
thanks for the review!
wondering whether we should mark `topic` as `optional` in order to maximise backwards compatibility out of the box?

**Comment by boks1971** [comment]
> thanks for the review! wondering whether we should mark `topic` as `optional` in order to maximise backwards compatibility out of the box?

Isn't everything optional in protobuf?

**Comment by lukasIO** [comment]
I think without the _optional_ keyword the field will be populated with a default value, vs. the presence of the field being tracked explicitly. 
In the context of this `topic` that would mean an empty string. 
reference: https://github.com/protocolbuffers/protobuf/blob/v3.12.0/docs/field_presence.md#using-the-generated-code

I guess we can go with both options, the only downside being that a user defined topic with an empty string would be treated as no topic - which is ok, I guess?

**Comment by boks1971** [comment]
In that case, I think `optional` is good.

**Comment by frostbyte73** [comment]
We can't use optionals until protoc_gen_ruby is updated to support it:

```
livekit_models.proto: is a proto3 file that contains optional fields, but code generator protoc-gen-twirp_ruby hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--twirp_ruby_out:
```

**Comment by frostbyte73** [comment]
protoc-gen-twirp_ruby has been updated, ignore above

**Pull request merged**
