### PR TITLE
Added C# namespace + Unity SDK

### PR DESCRIPTION
**Pull request by FeepsDev**
Required for the Unity SDK

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]
looks good!

**Comment by davidzhao** [comment]
looks like there's a conflict with main, if you wanna merge and re-generate, we should be good to merge

**Comment by FeepsDev** [comment]
Is the conflict resolved ?

**Comment by davidzhao** [comment]
> Is the conflict resolved ?

yup, thank you!

**Pull request merged**
