### PR TITLE
Added metadata and tagging to S3

### PR DESCRIPTION
**Pull request by nkonev**
Hi,
I need to add the same metadata to the S3 uploaded files
Due to inability to add metadata via S3 api [without a copying](https://stackoverflow.com/a/38894571), I added it here in protocol.

Types are chosen according `s3.PutObjectInput` [here](https://github.com/livekit/egress/blob/3304f9aa2f5401100ab6c551c8a6543e5025235e/pkg/pipeline/sink/upload.go#L56).

### CODE REVIEW

**Comment by nkonev** [comment]
Hi
@frostbyte73 PTAL

**Comment by nkonev** [comment]
@davidzhao PTAL

**Comment by frostbyte73** [comment]
hey @nkonev, can you open the egress PR as well? We try to merge protocol changes and implementation together

**Comment by nkonev** [comment]
https://github.com/livekit/egress/pull/154

**Review by frostbyte73 — APPROVED** [review]

**Pull request merged**
