### PR TITLE
bytes -> string gcp credentials

### PR DESCRIPTION
**Pull request by frostbyte73**

### CODE REVIEW

**Comment by biglittlebigben** [comment]
Won't this break existing code?

**Comment by frostbyte73** [comment]
> Won't this break existing code?

https://protobuf.dev/programming-guides/proto/#updating
`string and bytes are compatible as long as the bytes are valid UTF-8.`

**Comment by frostbyte73** [comment]
the only difference in go should be that
```
&GCPUpload{
    Credentials: []byte("...")
}
```
changes to 
```
&GCPUpload{
    Credentials: "..."
}
```

**Review by davidzhao — APPROVED** [review]
lgtm, we should bump protocol by a minor version, should ensure that server SDKs have a minor version bump as well.

**Comment by frostbyte73** [comment]
> > the only difference in go should be that
> > ```
> > &GCPUpload{
> >     Credentials: []byte("...")
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > changes to
> > ```
> > &GCPUpload{
> >     Credentials: "..."
> > }
> > ```
> 
> Right, I was asking about SDK compatibility rather than protocol. Do we have a process to document these changes that will require code updates from SDK users?

Probably just release notes, we do not have a documented process

**Pull request merged**
