### PR TITLE
Adds Redis pool size and timeout

### PR DESCRIPTION
**Pull request by itzloop**
This is related to [#2238](https://github.com/livekit/livekit/issues/2238). It's a requirement to be able to configure redis pool size.

### CODE REVIEW

**Comment by itzloop** [comment]
Hi. Do you have any plans to review this PR?

**Comment by itzloop** [comment]
Hi. Would you happen to have any plans to go over this PR?

**Comment by itzloop** [comment]
Any updates on this?

**Review by davidzhao — APPROVED** [review]
looks good! sorry for the delays in getting to review.

**Pull request merged**
